### ISSUE TITLE
Can you contribute the ESP32 library to the KiCad repository?

### ISSUE THREAD

**Issue by taotieren** [espressif/kicad-libraries#1]
Can you contribute the ESP32 library to the [KiCad repository](https://gitlab.com/kicad/libraries)?

https://www.kicad.org/libraries/contribute/
https://www.kicad.org/libraries/klc/

**Comment by pedrominatel** [comment]
Hi @taotieren, we are working on the first version of this library to include all commercial SoC and modules.
As soon as we have the first version available, we can do that.

**Comment by taotieren** [comment]
I hope to contribute these libraries to the library warehouse before V6 is released, so that V6 users can directly use the ESP library to make PCB files

**Comment by pedrominatel** [comment]
For sure @taotieren!
