### ISSUE TITLE
Symbol ESP32-S3-WROOM-1 wrong name

### ISSUE THREAD

**Issue by TDA-2030** [espressif/kicad-libraries#10]
## Description
The two names in the red box are different
![WXWorkCapture_16281608963857](https://user-images.githubusercontent.com/39872773/128338877-d308ba9e-a7ea-41e7-981a-1044530c1801.png)

**Comment by pedrominatel** [comment]
Thanks for pointing this out @TDA-2030. This will be fixed soon.

**Comment by pedrominatel** [comment]
PTAL @TDA-2030 before merging.

https://github.com/espressif/kicad-libraries/pull/13

**Comment by TDA-2030** [comment]
LGTM :)
