### ISSUE TITLE
Archive does not contain a valid metadata.json when Installing kicad-libraries-1.1.0.zip

### ISSUE THREAD

**Issue by Bjurestrand** [espressif/kicad-libraries#105]
I think I may be doing something wrong. When I try to install kicad-libraries-1.1.0.zip, I receive the following error: "Archive does not contain a valid metadata.json.

**Comment by meakashrao** [comment]
As far as I can Tell, I am directly downloading the main branch zip and tag 2.0.3 zip, so I couldn't be using the wrong file. 

Please can you help me with the one that's working for you.
