### ISSUE TITLE
missing the SoC footprints :)

### ISSUE THREAD

**Issue by ESP32DE** [espressif/kicad-libraries#113]
missing the SoC footprints :)

![image](https://github.com/espressif/kicad-libraries/assets/16070445/d28ff9ee-ef9f-48c1-bd73-aba4802998a3)

**Comment by pedrominatel** [comment]
Hi @ESP32DE

For the SoC, the footprint used is from the default KiCad library, as you can see here:

![image](https://github.com/espressif/kicad-libraries/assets/274658/c4344272-a5f6-4fa2-bc87-9cd43b26a175)

**Comment by ESP32DE** [comment]
hi @pedrominatel thanks
i used kicad 7 without the default KiCad library for a test - ( just only 140 Mb, with the default KiCad library 1.1GB  )
i will cpy the parts from the default KiCad library 6 and convert them .
thanks
