### ISSUE TITLE
Which footprint for ESP32-S3-PICO-1

### ISSUE THREAD

**Issue by lclaude** [espressif/kicad-libraries#123]
Hello,
I'm not sure which footprint to use with the SoC ESP32-S3-PICO-1.
In the datasheet the package is LGA56 (7x7mm), I can't find an equivalent in your footprints.
Thanks by advance.

**Comment by pedrominatel** [comment]
Hi @lclaude,

You can use the **QFN-56 1EP 7x7mm P0.4mm EP4x4mm** from the official KiCad library.

**QFN-56-1EP_7x7mm_P0.4mm_EP4x4mm**

![Screenshot 2023-10-10 at 08 14 07](https://github.com/espressif/kicad-libraries/assets/274658/32497de5-70f2-4383-8e9b-2ce80f89eecf)

Equivalent to the LGA-56

![Screenshot 2023-10-10 at 08 14 23](https://github.com/espressif/kicad-libraries/assets/274658/b4b1bc8d-161c-49ff-bc85-a6159deb758f)

**Comment by lclaude** [comment]
OK, I'll test with this one. Thank you.
