### ISSUE TITLE
Any plans for the ESP32-C3-DevKitM-1?

### ISSUE THREAD

**Issue by electron271** [espressif/kicad-libraries#124]

**Comment by pedrominatel** [comment]
Hi @electron271, we can add it.

[ESP32-C3-user-guide-devkitm-1](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitm-1.html)

![Screenshot 2023-10-13 at 08 17 48](https://github.com/espressif/kicad-libraries/assets/274658/bc962b35-ffb4-490e-8e46-a2138fec4ce1)

**Comment by electron271** [comment]
Thanks! I normally would have made a PR, however I am very bad at making KiCad footprints

**Comment by pedrominatel** [comment]
Don't worry!

**Comment by electron271** [comment]
Looked at PR, the footprint seems fine, haven't tested the symbol yet though

**Comment by pedrominatel** [comment]
I'll merge soon.
