### ISSUE TITLE
Kicad 7.0.6->Archive does not contain a valid metadata.json file

### ISSUE THREAD

**Issue by meakashrao** [espressif/kicad-libraries#132]
Hello, I tried to install from Main Release or Branch Release and metadata error keeps popping up. 

Please advise what to do.
<img width="575" alt="image" src="https://github.com/espressif/kicad-libraries/assets/120377875/f9dd5dfe-5ac5-4299-b21c-880e36e4a9e1">

Regards,
Akash Rao

**Comment by pedrominatel** [comment]
Hi,
Can you check this issue #105 if it is related to yours?

**Comment by meakashrao** [comment]
No, I don't think so, I went ahead and downloaded 7.0.9 Kicad, could you please help me with the latest release branch so that I can try that out

**Comment by meakashrao** [comment]
https://github.com/espressif/kicad-libraries/releases/tag/2.0.4

We'll sorry this did work for me.

Thanks for the help
