### ISSUE TITLE
Symbol and Footprint for ESP32-C3-DevKitC-02

### ISSUE THREAD

**Issue by dougli1sqrd** [espressif/kicad-libraries#134]
It looks like there are symbols and footprints for the ESP32-C3-DevKitM, but I would also love to have available the DevKitC, user guide linked here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/hw-reference/esp32c3/user-guide-devkitc-02.html.

Are there any plans to make this symbol/footprint?

**Comment by pedrominatel** [comment]
Hi @dougli1sqrd, we can add the DevKitC.
Thanks!
