### ISSUE TITLE
metadata.json is missing in the release files

### ISSUE THREAD

**Issue by muexxl** [espressif/kicad-libraries#136]
I just downloaded the release file 2.0.5.  and got an import error "... metadata.json is missing". 
I was able to create the metadata.json file by cloning the package and running the package.py script. 
You may want to include the metadata.json file in future releases.

**Comment by Joebeazelman** [comment]
Interesting. I downloaded the zip file and it contains the metadata.json, but couldn't get KiCad 7 to open it from MacOS.

**Comment by pedrominatel** [comment]
Please take a look at https://github.com/espressif/kicad-libraries/issues/112

**Comment by pedrominatel** [comment]
Closing the issue. Related to the issue #137.
