### ISSUE TITLE
Can't install library in Kicad 7 for MacOS

### ISSUE THREAD

**Issue by Joebeazelman** [espressif/kicad-libraries#137]
I'm running macOS Sonoma and KiCad 7.0. I've downloaded the latest KiCad Library addon zip file (version 2.0.5) and tried to install it using **Install from File...** from the **Plugin and Content Manager**. I was able to see a grayed out  **metadata,.json**, but I was unable to select it. 

I thought it may be installed automatically, but I didn't see the library installed.

Please advise?

**Comment by pedrominatel** [comment]
Hello,
Are you using Safari to download the ZIP file?

PTAL https://github.com/espressif/kicad-libraries/issues/112

**Comment by jacobnrohan** [comment]
Is there a suggested solution? #112 doesn't specify a solution.

I've download using both `github.com -> download ZIP` and using `git clone https://github.com/espressif/kicad-libraries` and re-zipping the file. Both methods result in **Archive does not contain a valid metadata.json** error message in Kicad 7.0.7. The same is true after I upgraded to Kicad 7.0.9.

**Comment by pedrominatel** [comment]
Have you tried this [file](https://github.com/espressif/kicad-libraries/releases/download/2.0.5/espressif-kicad-addon.zip) from the assets, @jacobnrohan?

**Comment by ariyyyaaannn** [comment]
macOS automatically unzips compressed files when downloaded. If you 'rezip' this folder, you get the following file structure:

```
>espressif-kicad-addon.zip
   >espressif-kicad-addon
      >3dmodels
      >footprints
      >metadata.json
      >....

```
  
As @jacobnrohan mentioned, You need the contents of the 'espressif-kicad-addon' to be at the root of the .zip file. Instead, select the contents of the downloaded folder and recompress them into a new .zip file. This is the desired structure:

```
>Archive.zip
   >3dmodels
   >footprints
   >metadata.json
   >....
```

You should be able to upload this new archive to the Kicad PCM with no issue.

<img width="562" alt="image" src="https://github.com/espressif/kicad-libraries/assets/81991527/633590c0-c29f-47e7-b7fc-aeac00c8ffb1">

**Comment by pedrominatel** [comment]
Hi @ariyyyaaannn,

Thank you for the detailed explanation. This information about Safari "Open safe..." preference will be included on the README file soon.

**Comment by pedrominatel** [comment]
Closing this issue. Now we have a note on the readme.
