### ISSUE TITLE
Missing 3D model of ESP32-S3-MINI-1U

### ISSUE THREAD

**Issue by ONLYA** [espressif/kicad-libraries#139]
I found that there was an issue related to this model: #58 . However, I cannot find the 3D model for ESP32-S3-MINI-1U in the repo now even if it was said to be done.
If the model was there but got deleted during version branch transition, could you please add them back to the library?

**Comment by pedrominatel** [comment]
Done, @ONLYA. Please take a look at the release v2.0.6.

**Comment by ONLYA** [comment]
> Done, @ONLYA. Please take a look at the release v2.0.6.

Thank you pedrominatel!
