### ISSUE TITLE
ESP32-S3-MINI-1 symbol references "ESP32-S3-WROVER" 

### ISSUE THREAD

**Issue by atanisoft** [espressif/kicad-libraries#22]
A rather minor issue in the symbol:
https://github.com/espressif/kicad-libraries/blob/b40df1bc7486e5b6350e0c265a6b5adb9419a549/libraries/Espressif.lib#L789

**Comment by pedrominatel** [comment]
Thanks for your feedback @atanisoft. This will be fixed soon.
