### ISSUE TITLE
do you can add altium libraries for it

### ISSUE THREAD

**Issue by yuyue2013** [espressif/kicad-libraries#44]
I use the altium for drawing board.  but the esp32 don't have the altium libraries. do you can add altium libraries of esp32?  thanks!

**Comment by TianmingLi** [comment]
if you use altium, you can get everything from [lceda](https://lceda.cn/editor). also there are lot tutorial for how to do it.

**Comment by pedrominatel** [comment]
Hi,

Espressif does not have any plans in the near future for adding the Altium libraries.
