### ISSUE TITLE
README is confusing

### ISSUE THREAD

**Issue by blackketter** [espressif/kicad-libraries#5]
It's not clear when you arrive on the GitHub page for this library where the referenced footprints and symbols are.  

I suggest that either:

The README.md should be updated to reference the appropriate branches
or

Include the 5.0-compatible files in the Main branch and leave the 6.0 versions in a branch to be merged later (after 6.0 is released)

or 

Include folders for each major version of KiCAD in the Main branch

**Comment by pedrominatel** [comment]
Thanks @blackketter for the feedback. We will improve that.

The `legacy` will be merged soon to main and all KiCad V6 libs will be removed.
