### ISSUE TITLE
esp32-mini-1 symbol / footprint

### ISSUE THREAD

**Issue by tenderlove** [espressif/kicad-libraries#56]
Hi,

I'm working on a project that incorporates the [esp32-mini-1](https://www.espressif.com/sites/default/files/documentation/esp32-mini-1_datasheet_en.pdf), and I was wondering if there is a KiCad symbol / footprint available for that module?  I don't see one in this repository, but I would be happy to make one if there is a similar module I can copy from.

Any help would be greatly appreciated.

Thanks!

**Comment by pedrominatel** [comment]
Thanks, @tenderlove. We can provide the new footprint/symbol for this new module.
This module has a different landing pad number from all the other MINI versions. Copy is not possible.

**Comment by tenderlove** [comment]
@pedrominatel awesome, thank you!!! 😍

**Comment by tenderlove** [comment]
@pedrominatel thanks for fixing this!  I don't see the mini-1 in the repo though.  Am I missing something?  Thanks.
