### ISSUE TITLE
Adherence to KiCad Library Conventions

### ISSUE THREAD

**Issue by JustinOng** [espressif/kicad-libraries#57]
Hello,

Can I find out if there are plans to have the symbols to adhere to the [KiCad Library Conventions](https://klc.kicad.org/symbol/)? The two specifically I've noticed on the ESP32-WROOM-E:

- S4.1, point 1, where the pin origin should lie on a 100mil grid
- S4.3, point 3, where pins of the same type (mostly GND) should be stacked together

**Comment by pedrominatel** [comment]
Hi @JustinOng, thank you for the concern. I'll review this issue and make the changes.

**Comment by pedrominatel** [comment]
Can you take a look at PR #61, @JustinOng?
