### ISSUE TITLE
Models for ESP32-S3-MINI-1U and ESP8684-MINI-1-H4

### ISSUE THREAD

**Issue by GTCLive** [espressif/kicad-libraries#58]
Hi guys, would it be possible to update this repo with the latest step files for S3 and C2, please?
Those are the modules we've recently bought and can't find them in the repo. 
No rush neither an impediment in getting PCB done.
Would be nice to have that's all.
Thanks

ESP32-S3-MINI-1U
ESP8684-MINI-1-H4
ESP8684-WROOM-01C-H4

**Comment by pedrominatel** [comment]
Done, @GTCLive.
