### ISSUE TITLE
3D model of ESP32-S3-WROOM-1U

### ISSUE THREAD

**Issue by dangvitin** [espressif/kicad-libraries#59]
I think the 3D model for **ESP32-S3-WROOM-1U** is not correct.

![image](https://user-images.githubusercontent.com/48706116/195165614-84f44ab7-61ba-45a0-8e1a-81072b2bee79.png)

**Comment by pedrominatel** [comment]
Thank you @dangvitin, for reporting this issue.
I'll take a look.

**Comment by pedrominatel** [comment]
Hi,

In fact, this 3D model is the wrong one and will be removed from the 3D folder. The correct one will be uploaded as soon as possible.
