### ISSUE TITLE
Thermal pads of ESP32-WROOM-E at wrong location?

### ISSUE THREAD

**Issue by timcooijmans** [espressif/kicad-libraries#62]
Hi,

Our PCBA house noted a mismatch (both in X and Y location as size) between the thermal pads of ESP32-WROOM-E in this library and the datasheet (in red):
![image](https://user-images.githubusercontent.com/3218488/200275986-f6689d21-e20d-48b1-93a6-3c0b7b0fe17d.png)

Footprint 8.32mm to center of thermal pads:
![image](https://user-images.githubusercontent.com/3218488/200276331-6bf46f0c-f60b-4988-b6b8-d5c786e1807a.png)

Datasheet 7.5mm to center of thermal pads:
![image](https://user-images.githubusercontent.com/3218488/200276620-4eda9204-0877-4be9-9de7-322e29b2f341.png)

Same applies in the vertical direction and the size of the pads themselves.

**Comment by pedrominatel** [comment]
Thank you, @timcooijmans,  for your feedback. This issue has been fixed and merged.
Please check it out.
