### ISSUE TITLE
Feature Request: Add KICAD Library to Offical PCM (Package and Plugin Manager)

### ISSUE THREAD

**Issue by philippdonabauer** [espressif/kicad-libraries#65]
### Kicad PCM (Plugin and Content Manager) Feature Request

Kicad now provides the possibility to add custom footprint / content libraries to a Plugin Manager. This provide the users the possibility to simple install Offical released versions of your content library. It also helps you to be one of the first "microcontroller" on the platform that also means that you can arrive more and new customers.

Here an screenshot of the library manager, which i think is one of the biggest new features:

<img width="1069" alt="Bildschirmfoto 2022-12-07 um 22 03 51" src="https://user-images.githubusercontent.com/9103242/206295579-464d425c-5bfa-4d8a-902b-3be5bc455668.png">

The documentation is simple to understand: https://dev-docs.kicad.org/en/addons/

I would love to see this package in the plugin manager in the future. I maybe also can help a little bit if you don't have the time to do that.

Thank you very much.

**Comment by pedrominatel** [comment]
Hi @philippdonabauer,

This has been on my to-do list for a while. I'll start working on that by Jan/Feb 23.

**Comment by pedrominatel** [comment]
Hi, @philippdonabauer. It will be great if you contribute to this project! Go ahead!
Many thanks for your help!

**Comment by dronecz** [comment]
@philippdonabauer Any progress with this? Many thanks for your work! :heart:

**Comment by cooked** [comment]
@philippdonabauer I've developed a gitHub action to automate packaging of Kicad addon... maybe it can help your case. let me know if you try it out and need help 
https://github.com/marketplace/actions/publish-kicad-addon

cheers

**Comment by pedrominatel** [comment]
Thank you @philippdonabauer for your help!

As I understood, you are able to install via the ZIP file but you can't find the package in the libraries search, is that correct?

**Comment by pedrominatel** [comment]
One good example we can follow is the `keyswitch-kicad-library` from @perigoso: https://github.com/perigoso/keyswitch-kicad-library

Is there anything you can help us with, @perigoso?

**Comment by perigoso** [comment]
Hi, probably, but i would need to understand the problem first, I'll take a look at the end of the day

**Comment by perigoso** [comment]
Sorry, I didn't have time and then forgot...

I'm sorry to inform you I have nothing to add. :sweat_smile: 

Your branch looks good, the generated package has the correct structure and everything looks good, it installs and I can find the libraries just fine.

Do make sure the libraries are in the footprint and symbol library tables, in Preferences, when the feature was added libraries were not added automatically, but right now I think they are supposed to.

**Comment by perigoso** [comment]
IMO the patch is good to go as is, the problem is either a bug on the version of KiCad you are using or some configuration issue

**Comment by JarrettR** [comment]
Hi,

Is this good to just create a PR?

**Comment by JarrettR** [comment]
Works fine on Windows

![image](https://user-images.githubusercontent.com/6027644/233457957-79fc57af-aa63-459c-a244-e35f8afa37f9.png)


Added quick rough directions on how to submit to KiCad. It's from memory, so it's possible it's not fully complete, but the gist of it is there.
