### ISSUE TITLE
ESP32-WROOM symbol missing GND pins

### ISSUE THREAD

**Issue by cooked** [espressif/kicad-libraries#74]
library version 1.1.0 pin missing:
- pin 15
- pin 38

![image](https://user-images.githubusercontent.com/1381353/215446576-3b980665-4f34-496e-aff0-3929b44ac453.png)

**Comment by pedrominatel** [comment]
Hi,

All GND pins are grouped together and just one is visible. You can see the symbols in the full pin list.

![image](https://user-images.githubusercontent.com/274658/215722261-63342641-9c13-4458-8ff6-957967e0ebd7.png)
