### ISSUE TITLE
Off grid pin 9 in ESP32-C3-WROOM-02 symbol

### ISSUE THREAD

**Issue by sevesalm** [espressif/kicad-libraries#77]
Pin 9 in ESP32-C3-WROOM-02 symbol has off grid x position. Gives the following warning in KiCad 7 symbol editor: `Off grid pin 9 'GND' at location (-0.0054 mm, 27.9400 mm). I guess it should just be 0 mm. 

The affected line:
https://github.com/espressif/kicad-libraries/blob/main/libraries/Espressif.kicad_sym#L739

**Comment by pedrominatel** [comment]
Thank you for your report, @sevesalm! We'll take care ASAP.
