### ISSUE TITLE
Keepout zones over antenna regions

### ISSUE THREAD

**Issue by DanielVoogsgerd** [espressif/kicad-libraries#78]
In the datasheets for various modules one can find that there is a keepout zone where the antenna is, this makes sense. However, I don't see such a keepout zone in the footprints. Is this for a specific reason I'm not seeing? If it isn't, it might be a good addition to the footprints.

**Comment by pedrominatel** [comment]
Hi @DanielVoogsgerd,

I believe this will bring good value to the designers. I'll add the keepout zones for the new fp's and review/bug fix the others.

**Comment by DanielVoogsgerd** [comment]
Terrific, if I can be of any assistance feel free to say so. I suspect however that reviewing the keepout zones would be about as much work as drawing them. If it isn't I'm happy to create a PR with the changes.
