### ISSUE TITLE
Document how to get 3D models working correctly

### ISSUE THREAD

**Issue by blackketter** [espressif/kicad-libraries#8]
I see the 3d models in the repository, but they are not referenced correctly in the footprint files.  There seems to be a missing ${ESPRESSIF_3DMODELS} definition in the path.  This should be documented in the README as part of installation instructions.

Ideally, there would be a default relative path that would work without any further setup, but I don't think Kicad5 has a facility for this.

**Comment by pedrominatel** [comment]
Thanks for the feedback. We'll include this step on README.
