### ISSUE TITLE
There are no 3 and 56 pins in ESP32-S3 chip symbol

### ISSUE THREAD

**Issue by tanklist** [espressif/kicad-libraries#88]
There are no 3 and 56 pins in ESP32-S3 chip symbol.

**Comment by pedrominatel** [comment]
Hi, @tanklist.

Those pins are grouped and hidden.

![image](https://user-images.githubusercontent.com/274658/232703176-f9c7a01b-0fda-42ae-b983-c35c9fc0f5b1.png)
