### ISSUE TITLE
Plans for ESP32-C6-MINI-1U?

### ISSUE THREAD

**Issue by jessebraham** [espressif/kicad-libraries#90]
The `ESP32-C6-MINI-1` has a symbol/footprint, however there does not appear to be a footprint for the `U` variant of this module. Were there plans to add this?

**Comment by pedrominatel** [comment]
Hi @jessebraham,

Yes, the `U` variant will be supported by this library soon. The footprint will be pin-to-pin compatible with the `non-U` variant.

**Comment by jessebraham** [comment]
Awesome, thanks Pedro!
