### ISSUE TITLE
plan for ESP32-C6-DevKitM-1 ?

### ISSUE THREAD

**Issue by tomlevisse** [espressif/kicad-libraries#96]
Are you going to add ESP32-C6-DevKitM-1 to the library ?

**Comment by tomlevisse** [comment]
3D model will be available in this issue ?

**Comment by pedrominatel** [comment]
For reference: [ESP32-C6-devkitm-1-user_guide](https://docs.espressif.com/projects/espressif-esp-dev-kits/en/latest/esp32c6/esp32-c6-devkitm-1/user_guide.html#getting-started)

![Screenshot 2023-10-13 at 08 21 12](https://github.com/espressif/kicad-libraries/assets/274658/e112cae5-88af-41b1-8b93-dfdc15eaf0aa)

**Comment by tomlevisse** [comment]
@pedrominatel is it possible to add the 3D shape?
